### ISSUE TITLE
Add localization to French

### ISSUE THREAD

**Issue by jhonatasrm** [jhonatasrm/print-preview#14]
**Actual behavior**
The strings in [messages.json](https://github.com/jhonatasrm/print-preview/blob/master/src/_locales/fr/messages.json) are in English.

**Expected behavior**
The strings in [messages.json](https://github.com/jhonatasrm/print-preview/blob/master/src/_locales/fr/messages.json) needs to be localized to French.

**Comment by mamadou-diallo** [comment]
I can make the french translation if you would like

**Comment by jhonatasrm** [comment]
> I can make the french translation if you would like

Will be awesome! Thank you! 🙂
