### ISSUE TITLE
If I uninstall this addon (Ctrl+P) stops working... you have any idea why?

### ISSUE THREAD

**Issue by vassilyzaitsev** [jhonatasrm/print-preview#16]
If I uninstall this addon (Ctrl+P) stops working, does nothing... you have any idea why?

**Comment by jhonatasrm** [comment]
Hi there!
That is new... 🤔  

The shortcut for the Add-on is Ctrl + Shift + U (Windows). Did u change to Ctrl + P and after uninstall lost the shortcut? If that happened u can see an Add-on and set again the shortcuts (I will take a look at the Add-on if that happens to me).

**Comment by vassilyzaitsev** [comment]
I'm so sorry. I had an autohotkey script messing around with my shortcuts 😅  thanks!
