### ISSUE TITLE
Context Menu Icon for Dark Mode (System)

### ISSUE THREAD

**Issue by archetyped** [jhonatasrm/print-preview#18]
Hi, it would be great if the context menu icon is changed when the system-level dark mode is enabled.  Currently, when the system-level dark mode is enabled, the context menu background is also dark, so the black icon is difficult to see.

Thanks.

**Comment by jhonatasrm** [comment]
Hi!
Thank you very much for your feedback, adjusting that right now.

🙂

**Comment by archetyped** [comment]
Thanks for the update.  The blue icon is easier to see than the black icon in a context menu with a dark background.  However, perhaps a future update could use the same white icon that is used in the browser's toolbar for consistency and because it is less busy than the blue icon.
