### ISSUE TITLE
Print Preview disappears from context menu

### ISSUE THREAD

**Issue by gsmadrid** [jhonatasrm/print-preview#2]
I enabled the context menu feature and works great but after restarting Firefox I have to disable then enable the add-on.

**Comment by jhonatasrm** [comment]
Thank you for opening this issue. I will try to reproduce and then launch a fix.

**Comment by gsmadrid** [comment]
FYI,

I get the same result on two different computers, one Windows the other Linux.  Both using Firefox 67.0.1 64bit.

**Comment by jhonatasrm** [comment]
I released a update to fix the issue. Please check if possible.

**Comment by gsmadrid** [comment]
Thanks you so much, the latest version 1.4.1 not keeps the saved changes.  I will be sure to give you a good review.

**Comment by jhonatasrm** [comment]
Great! If you find any bugs, have suggestions for this or another Add-on, please feel free to open a new issue.

=)
