### ISSUE TITLE
Simplify the icon for Print Preview

### ISSUE THREAD

**Issue by stuckfly** [jhonatasrm/print-preview#9]
I use a high resolution display at the maximum pixel density. So, icons that are not minimalist are usually indistinguishable. If you keep the printer shape in the middle of your icon and get rid of all the border graphics around it, you will have an instantly recognizable icon. Printer. It's clear. And you can maximize its dimensions so it's even more obvious. The purpose of an icon is to indicate a function; not to look nice. But I'll keep using the add-on anyway and I hope you enjoy your coffee:)

**Comment by jhonatasrm** [comment]
I'm thinking of using the icon of a printer (the same icon of <a href="https://design.firefox.com/icons/viewer/#">printer used in Firefox</a>), changing accordingly the theme.

Thank you so much for your Coffee, I really appreciate. 🙂

**Comment by jhonatasrm** [comment]
The Add-on was updated at the <a href="https://addons.mozilla.org/en-US/firefox/addon/print-preview-/">Add-on page</a>. 

Thank you for open this issue! Any problems or doubts, please let me know.

:)
